name: deploy to Cloud Run

on:
  push:
    branches:
      - master
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE_TAG_NAME: asia.gcr.io/$GCP_PROJECT/spanner:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v1
      - name: authenticate GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "275.0.0"
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build --target deployment -t $IMAGE_TAG_NAME .

      - name: Push the docker image
        run: docker -- push $IMAGE
      # Comment in this job If you want to automate the switching of Cloud Run version
      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy foobar --image $IMAGE --project $GCP_PROJECT \
      #     --region $GCP_REGION --platform managed --quiet
